version = 0.1
[default.deploy.parameters]
stack_name = "ais-main-ch-2"
resolve_s3 = true
s3_prefix = "ais-main-ch-2"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\" ApiStageName=\"v1\" VpcStackName=\"vpc\" PermissionsBoundary=\"none\" CSLSSubscriptionEndpointArn=\"arn:aws:logs:eu-west-2:885513274347:destination:csls_cw_logs_destination_prodpython-2\" CodeSigningConfigArn=\"none\" CoreStackName=\"ais-core\" ProductTagValue=\"GOV.UK One Login\" SystemTagValue=\"Account Interventions Service\" OwnerTagValue=\"PLACEHOLDER\" SourceTagValue=\"govuk-one-login/account-interventions-service/src/infra/main/template.yaml\""
image_repositories = []
