version = 0.1
[default.deploy.parameters]
stack_name = "ais-main-ch"
resolve_s3 = true
s3_prefix = "ais-main-ch"
region = "eu-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\" VpcStackName=\"vpc\" PermissionsBoundary=\"none\" CoreStackName=\"ais-core-ch\""
image_repositories = []
