AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >-
  Main template for the account interventions service solution

Parameters:
  Environment:
    Description: The name of the environment to deploy to
    Type: String
    AllowedValues:
      - dev
      - build
      - staging
      - integration
      - production
    Default: dev
  VpcStackName:
    Description: The name of the stack that defines the VPC
    Type: String
    Default: vpc
    AllowedPattern: ^[a-z0-9-]+$
    ConstraintDescription: must be a valid organization ID, made of lowercase letters and numbers
  PermissionsBoundary:
    Description: The ARN of the permissions boundary to apply when creating IAM roles
    Type: String
    Default: none
  CodeSigningConfigArn:
    Description: Asserts that lambdas are signed when deployed.
    Type: String
    Default: none
  CoreStackName:
    Description: The name of the Core VC Storage stack
    Type: String
    Default: account-interventions-service-core
  ProductTagValue:
    Description: Value for the Product Tag
    Type: String
    Default: GOV.UK One Login
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Account Interventions Service
  OwnerTagValue:
    Description: Value for the Owner Tag
    Type: String
    Default: PLACEHOLDER
  SourceTagValue:
    Description: Value for the Source Tag
    Type: String
    Default: govuk-one-login/account-interventions-service/src/infra/main/template.yaml

Conditions:
  UsePermissionsBoundary: !Not [ !Equals [ !Ref PermissionsBoundary, 'none' ] ]
  UseCodeSigning: !Not [ !Equals [ !Ref CodeSigningConfigArn, 'none' ] ]

Mappings:
  EnvConfig:
    dev:
      LambdaLogLevel: DEBUG
    build:
      LambdaLogLevel: INFO
    staging:
      LambdaLogLevel: INFO
    integration:
      LambdaLogLevel: INFO
    production:
      LambdaLogLevel: INFO

Globals:
  Function:
    Runtime: nodejs18.x
    Architectures:
      - arm64
    Tracing: Active
    AutoPublishAlias: latest
    Environment:
      Variables:
        LOG_LEVEL: !FindInMap [ EnvConfig, !Ref Environment, LambdaLogLevel ]
        POWERTOOLS_SERVICE_NAME: !Ref AWS::StackName
        CLOUDWATCH_METRICS_NAMESPACE: !Ref SystemTagValue
    VpcConfig:
      SubnetIds:
        - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdA
        - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdB
        - Fn::ImportValue: !Sub ${VpcStackName}-ProtectedSubnetIdC
      SecurityGroupIds:
        - Fn::ImportValue: !Sub ${VpcStackName}-AWSServicesEndpointSecurityGroupId

Resources:
  AISSampleLambdaFunction:
    Type: AWS::Serverless::Function
    # checkov:skip=CKV_AWS_116: DLQ is not appropriate for a Lambda invoked by an API
    # checkov:skip=CKV_AWS_115: Function is not configured for function-level concurrent execution Limit
    Properties:
      FunctionName: !Sub '${AWS::StackName}-AISSampleLambdaFunction'
      CodeUri: ../../../dist/handlers/sample-lambda-handler
      Timeout: 10
      Environment:
        Variables:
          TABLE_NAME:
            Fn::ImportValue: !Sub "${CoreStackName}-AccountStatusTableName"
          METRIC_SERVICE_NAME: !Sub "${AWS::StackName}-SampleLambda"
      Handler: sample-lambda-handler.handle
      Role: !GetAtt AISSampleLambdaHandlerRole.Arn
      Tags:
        CheckovRulesToSkip: CKV_AWS_116.CKV_AWS_115
        Product: !Ref ProductTagValue
        System: !Ref SystemTagValue
        Environment: !Ref Environment
        Owner: !Ref OwnerTagValue
        Source: !Ref SourceTagValue

  AISSampleLambdaHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:  !Sub '${AWS::StackName}-AISSampleLambdaHandlerRole'
      PermissionsBoundary: !If [ UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  AISSampleLambdaHandlerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-AISSampleLambdaHandlerPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "dynamodb:PutItem"
              - "dynamodb:Query"
              - "dynamodb:DeleteItem"
              - "dynamodb:UpdateItem"
            Resource:
              - Fn::ImportValue: !Sub "${CoreStackName}-AccountStatusTableArn"
      Roles:
        - !Ref AISSampleLambdaHandlerRole

  InterventionProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-InterventionProcessorFunction"
      Description: "A Lambda function for processing the interventions."
      CodeUri: ../../../dist/interventions-processor-handler
      Timeout: 5
      Handler: interventions-processor-handler.handler
      Role: !GetAtt InterventionProcessorFunctionRole.Arn
      CodeSigningConfigArn: !If [ UseCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue ]
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TxMAIngressQueue.Arn
            BatchSize: 1
            FunctionResponseTypes:
              - ReportBatchItemFailures
      Environment:
        Variables:
          METRIC_SERVICE_NAME: "InterventionProcessorFunction"
          TABLE_NAME:
            Fn::ImportValue: !Sub "${CoreStackName}-AccountStatusTableName"
      Tags:
        Product: !Ref ProductTagValue
        System: !Ref SystemTagValue
        Environment: !Ref Environment
        Owner: !Ref OwnerTagValue
        Source: !Ref SourceTagValue
        CheckovRulesToSkip: CKV_AWS_116.CKV_AWS_115

  InterventionProcessorFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-InterventionProcessorFunctionRole"
      Description: !Sub "The role assumed by ${AWS::StackName}-InterventionProcessorFunction"
      PermissionsBoundary: !If [ UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue ]
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  InterventionProcessorFunctionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AWS::StackName}-InterventionProcessorFunctionPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              - !GetAtt InterventionProcessorFunctionLogGroup.Arn
          - Effect: Allow
            Action:
              - "sqs:ReceiveMessage"
              - "sqs:DeleteMessage"
              - "sqs:GetQueueAttributes"
            Resource: !GetAtt TxMAIngressQueue.Arn
          - Effect: Allow
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
            Resource: !GetAtt TxMAIngressEncryptionKey.Arn
          - Effect: Allow
            Action:
              - "dynamodb:UpdateItem"
              - "dynamodb:Query"
            Resource:
              - Fn::ImportValue: !Sub "${CoreStackName}-AccountStatusTableArn"
          - Effect: "Allow"
            Action:
              - "cloudwatch:PutMetricData"
            Resource:
              - "*"
            Condition:
              StringEquals:
                cloudwatch:namespace: !Ref SystemTagValue
      Roles:
        - !Ref InterventionProcessorFunctionRole

  InterventionProcessorFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${InterventionProcessorFunction}"
      RetentionInDays: 30
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue
        - Key: Name
          Value: !Sub "/aws/lambda/${InterventionProcessorFunction}"

  #### TxMA ####
  TxMAIngressEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: AWS KMS key for encrypting the contents of messages in TxMA SQS queues
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource:
              - "*"
          - Effect: Allow
            Principal:
              Service: sqs.amazonaws.com
            Action:
              - "kms:Decrypt"
              - "kms:GenerateDataKey"
            Resource: "*"
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:*"
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue
        - Key: Name
          Value: !Sub "${AWS::StackName}-TxMAIngressEncryptionKey"

  TxMAIngressEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-TxMAIngressEncryptionKey"
      TargetKeyId: !GetAtt TxMAIngressEncryptionKey.Arn

  TxMAIngressQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-TxMAIngressQueue"
      MessageRetentionPeriod: 1209600
      KmsMasterKeyId: !GetAtt TxMAIngressEncryptionKey.Arn
      RedriveAllowPolicy:
        redrivePermission: denyAll
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TxMAIngressDLQ.Arn
        maxReceiveCount: 3
      VisibilityTimeout: 5
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue

  TxMAIngressQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    DependsOn: TxMAIngressQueue
    Properties:
      Queues:
        - !Ref TxMAIngressQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - "sqs:SendMessage"
            Resource: !GetAtt TxMAIngressQueue.Arn
            Principal:
              Service: sns.amazonaws.com

  TxMAIngressDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-TxMAIngressDLQ"
      KmsMasterKeyId: !Ref TxMAIngressEncryptionKeyAlias
      VisibilityTimeout: 0
      MessageRetentionPeriod: 1209600
      RedriveAllowPolicy:
        redrivePermission: byQueue
        sourceQueueArns:
          - !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${AWS::StackName}-TxMAIngressQueue"
      Tags:
        - Key: Product
          Value: !Ref ProductTagValue
        - Key: System
          Value: !Ref SystemTagValue
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref OwnerTagValue
        - Key: Source
          Value: !Ref SourceTagValue
