version = 0.1
[default.deploy.parameters]
stack_name = "ais-alarm"
resolve_s3 = true
s3_prefix = "ais-alarm"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\" VpcStackName=\"vpc\" PermissionsBoundary=\"none\" CoreStackName=\"ais-core\""
image_repositories = []
