AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >-
  Alarm template for the Account Interventions Service (AIS) solution.

Parameters:
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Account Interventions Service
  AlertingSNSLowAlertNotificationTopicARN:
    Description: "The ARN of the Alerting SNS Low Alert Notification topic"
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/ais-infra-alerting/SNS/LowAlertNotificationTopic/ARN" #pragma: allowlist secret
  AlertingSNSHighAlertNotificationTopicARN:
    Description: "The ARN of the Alerting SNS High Alert Notification topic"
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/ais-infra-alerting/SNS/HighAlertNotificationTopic/ARN" #pragma: allowlist secret

#
# CloudWatch Alarms for SQS Queues
#

Resources:
  TxMAIngressQueueProcessingSlowly:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "The TxMA Ingress Queue is processing slowly."
      Namespace: AWS/SQS
      MetricName: TXMA_INGRESS_QUEUE_PROCESSING_SLOWLY
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: SampleCount
      Threshold: 60
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching

  TxMAIngressQueueProcessingTooSlowly:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSHighAlertNotificationTopicARN
      AlarmDescription: "The TxMA Ingress Queue is processing slowly."
      Namespace: AWS/SQS
      MetricName: TXMA_INGRESS_QUEUE_PROCESSING_TOO_SLOWLY
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: SampleCount
      Threshold: 600
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching

#
# CloudWatch Alarms for Updating Deletion Status
#
  AISUpdateDeleteFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "User's deletion status failed to be updated."
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      MetricName: MARK_AS_DELETED_FAILED
      Namespace: !Ref SystemTagValue
      Dimensions:
        - Name: service
          Value: AccountDeletionProcessorFunction
      Period: 60
      Statistic: Sum
      Unit: Count

  AISUpdateDeleteDDBError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "User's deletion status failed to be updated due to DynamoDB."
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      MetricName: DB_UPDATE_ERROR
      Namespace: !Ref SystemTagValue
      Dimensions:
        - Name: service
          Value: AccountDeletionProcessorFunction
      Period: 60
      Statistic: Sum
      Unit: Count

# Cloudwatch alarms for State Engine #
  AccountStateEngineConfigurationIssue:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSHighAlertNotificationTopicARN
      AlarmDescription: "There is a configuration issue with the Account State Engine."
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      Metrics:
        - Id: m1
          Label: "configuration file failed validation"
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: !Ref SystemTagValue
              MetricName: INVALID_STATE_ENGINE_CONFIGURATION
              Dimensions:
                - Name: service
                  Value: InterventionsProcessorFunction
            Period: 60
            Stat: Sum
        - Id: m2
          Label: "No intervention was found in configuration file for given code."
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: !Ref SystemTagValue
              MetricName: INTERVENTION_CODE_NOT_FOUND_IN_CONFIG
              Dimensions:
                - Name: service
                  Value: InterventionsProcessorFunction
            Period: 60
            Stat: Sum
        - Id: m3
          Label: "The applied intervention resulted in no state changes."
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: !Ref SystemTagValue
              MetricName: TRANSITION_SAME_AS_CURRENT_STATE
              Dimensions:
                - Name: service
                  Value: InterventionsProcessorFunction
            Period: 60
            Stat: Sum
        - Id: m4
          Label: "The user's state could not be found in current config file."
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: !Ref SystemTagValue
              MetricName: STATE_NOT_FOUND_IN_CURRENT_CONFIG
              Dimensions:
                - Name: service
                  Value: InterventionsProcessorFunction
            Period: 60
            Stat: Sum
        - Id: m5
          Label: "The current account state has no transitions in current config file."
          ReturnData: false
          MetricStat:
            Metric:
              Namespace: !Ref SystemTagValue
              MetricName: NO_TRANSITIONS_FOUND_IN_CONFIG
              Dimensions:
                - Name: service
                  Value: InterventionsProcessorFunction
            Period: 60
            Stat: Sum
        - Id: sum_of_occurrences
          Label: 'total number of configuration issues'
          ReturnData: true
          Expression: SUM([m1,m2,m3,m4,m5])

  InterventionNotAllowed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "Intervention received was not allowed on current account state."
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 5
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      MetricName: STATE_TRANSITION_NOT_ALLOWED_OR_IGNORED
      Namespace: !Ref SystemTagValue
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction
      Period: 120
      Statistic: Sum
      Unit: Count

  TooManyInterventionNotAllowed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSHighAlertNotificationTopicARN
      AlarmDescription: "Too many Interventions received were not allowed on current account state."
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 5
      EvaluationPeriods: 5
      TreatMissingData: notBreaching
      MetricName: STATE_TRANSITION_NOT_ALLOWED_OR_IGNORED
      Namespace: !Ref SystemTagValue
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction
      Period: 60
      Statistic: Sum
      Unit: Count
