AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: >-
  Alarm template for the Account Interventions Service (AIS) solution.

Parameters:
  SystemTagValue:
    Description: Value for the System Tag
    Type: String
    Default: Account Interventions Service
  AlertingSNSLowAlertNotificationTopicARN:
    Description: "The ARN of the Alerting SNS Low Alert Notification topic"
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/infra-alerting/SNS/LowAlertNotificationTopic/ARN" #pragma: allowlist secret
  AlertingSNSHighAlertNotificationTopicARN:
    Description: "The ARN of the Alerting SNS High Alert Notification topic"
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/infra-alerting/SNS/HighAlertNotificationTopic/ARN" #pragma: allowlist secret

#
# CloudWatch Alarms for SQS Queues
#

Resources:
  TxMAIngressQueueProcessingSlowly:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "The TxMA Ingress Queue is processing slowly."
      Namespace: AWS/SQS
      MetricName: TXMA_INGRESS_QUEUE_PROCESSING_SLOWLY
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: SampleCount
      Threshold: 60
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching

  TxMAIngressQueueProcessingTooSlowly:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSHighAlertNotificationTopicARN
      AlarmDescription: "The TxMA Ingress Queue is processing slowly."
      Namespace: AWS/SQS
      MetricName: TXMA_INGRESS_QUEUE_PROCESSING_TOO_SLOWLY
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: SampleCount
      Threshold: 600
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching

#
# CloudWatch Alarms for Updating Deletion Status
#
  AISUpdateDeleteFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "User's deletion status failed to be updated."
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      MetricName: MARK_AS_DELETED_FAILED
      Namespace: !Ref SystemTagValue
      Dimensions:
        - Name: service
          Value: AccountDeletionProcessorFunction
      Period: 60
      Statistic: Sum
      Unit: Count

  AISUpdateDeleteDDBError:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "User's deletion status failed to be updated due to DynamoDB."
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
      MetricName: DB_UPDATE_ERROR
      Namespace: !Ref SystemTagValue
      Dimensions:
        - Name: service
          Value: AccountDeletionProcessorFunction
      Period: 60
      Statistic: Sum
      Unit: Count

#
# Account Interventions Processor Alarms
#
  EventValidationFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "Intervention event failed validation."
      Namespace: !Ref SystemTagValue
      MetricName: INTERVENTION_EVENT_INVALID
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: Sum
      Threshold: 5
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction

  TooManyEventsValidationFailed:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSHighAlertNotificationTopicARN
      AlarmDescription: "Too many intervention events failed validation."
      Namespace: !Ref MainCloudWatchMetricNamespace
      MetricName: INTERVENTION_EVENT_INVALID
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: Sum
      Threshold: 5
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: notBreaching
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction

  InvalidEventReceived:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "Received intervention event is invalid."
      Namespace: !Ref SystemTagValue
      MetricName: INVALID_EVENT_RECEIVED
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: Sum
      Threshold: 5
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction

  TooManyInvalidEventsReceived:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSHighAlertNotificationTopicARN
      AlarmDescription: "Too many received intervention events are invalid."
      Namespace: !Ref MainCloudWatchMetricNamespace
      MetricName: INVALID_EVENT_RECEIVED
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: Sum
      Threshold: 5
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: notBreaching
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction

  AccountMarkedAsDeleted:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "Intervention event failed validation."
      Namespace: !Ref SystemTagValue
      MetricName: ACCOUNT_IS_MARKED_AS_DELETED
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: Sum
      Threshold: 5
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction

  InterventionIgnoredInFuture:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "Intervention event has timestamp in future."
      Namespace: !Ref SystemTagValue
      MetricName: INTERVENTION_IGNORED_IN_FUTURE
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: Sum
      Threshold: 5
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction

  InterventionEventStale:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSLowAlertNotificationTopicARN
      AlarmDescription: "Intervention event messages are out of order."
      Namespace: !Ref SystemTagValue
      MetricName: INTERVENTION_EVENT_STALE
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: Sum
      Threshold: 5
      EvaluationPeriods: 1
      Period: 60
      TreatMissingData: notBreaching
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction

  TooManyInterventionEventStale:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlertingSNSHighAlertNotificationTopicARN
      AlarmDescription: "Too many intervention event messages are out of order."
      Namespace: !Ref MainCloudWatchMetricNamespace
      MetricName: INTERVENTION_EVENT_STALE
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Statistic: Sum
      Threshold: 5
      EvaluationPeriods: 5
      Period: 60
      TreatMissingData: notBreaching
      Dimensions:
        - Name: service
          Value: InterventionsProcessorFunction
