version = 0.1
[default.deploy.parameters]
stack_name = "ais-core"
resolve_s3 = true
s3_prefix = "ais-core"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
