---
name: "Validate & Publish Core SAM Template"

on:
  push:
    branches:
      - main
    paths:
      - "src/infra/core/**"
      - ".github/workflows/merge-core-to-main.yaml"
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  validate_deployment:
    name: Deployment Template Checks
    uses: ./.github/workflows/validate-core-sam-template.yaml
    with:
      gitRef: ${{ inputs.gitRef }}
    secrets:
      githubActionsRoleARN: ${{ secrets.CORE_GH_ACTIONS_ROLE_ARN }}

  publish_artifacts:
    name: "Publish Image & Template"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
        with:
          ref: ${{ inputs.gitRef }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # pin@v1-node16
        with:
          role-to-assume: ${{ secrets.CORE_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: "Deploy SAM app"
        uses: govuk-one-login/devplatform-upload-action@2281463e2a4ea137fa3ff96b4620e5e39b01d7b7 # pin@v3.8.1
        with:
          artifact-bucket-name: ${{ secrets.CORE_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: ./src/infra/core/
          template-file: template.yaml

      - name: "Delegated Deployment via AWS CodeDeploy"
        run: echo "Deployment has been delegated to AWS CodeDeploy"
