---
name: 'Test Workflow'

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test_workflow:
    name: 'Test Workflow'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Step Placeholder
        run: echo "This workflow is designed for testing new workflows from feature branches that have not yet been merged into the main branch."

