---
name: Validate Main SAM Template

# Triggered when:
#   - a file, listed below, is pushed to any branch other than `main`, i.e. a feature branch.
#   - invoked by another workflow.
on:
  pull_request:
    paths:
      - src/infra/main/template.yaml
      - .github/workflows/validate-main-sam-template.yaml
  workflow_call:
    inputs:
      gitRef:
        required: false
        type: string
        default: ${{ github.ref }}
    secrets:
      githubActionsRoleARN:
        description: 'The GitHub actions role ARN passed from the caller workflow'
        required: false

jobs:
  validate_sam_template:
    name: SAM Checks
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      SAM_CLI_TELEMETRY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3
        with:
          ref: ${{ inputs.gitRef || github.sha }}
      - name: SAM Validate
        run: sam validate --lint -t src/infra/main/template.yaml
